---
- hosts: all
  become: true
  tasks:
    - name: Servers (deb)
      tags: deb_srv
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      register: apt_update_output
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Servers (rpm)
      tags: rpm_srv
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      register: dnf_update_output
      when: ansible_distribution in ['Rocky']

    - name: Check if reboot is required (deb)
      tags: deb_srv
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Check if reboot is required (rpm)
      tags: rpm_srv
      command: needs-restarting -r
      register: needs_restarting_output
      failed_when: false
      changed_when: false
      when: ansible_distribution in ['Rocky']

    - name: Prompt for reboot decision
      pause:
        prompt: "System requires a reboot. Would you like to reboot now? (yes/no)"
      register: reboot_prompt
      when: >
        (ansible_distribution in ['Debian', 'Ubuntu'] and reboot_required_file.stat.exists) or
        (ansible_distribution == ['Rocky'] and needs_restarting_output.rc == 1)

    - name: Reboot the server if confirmed
      tags: deb_srv,rpm_srv
      reboot:
        msg: "Reboot initiated by Ansible due to kernel update"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: >
        reboot_prompt.user_input is defined and 
        reboot_prompt.user_input | lower == 'yes'
