---
- hosts: all
  become: true
  tasks:
    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication\s+'
        line: 'PasswordAuthentication no'
        state: present
        validate: 'sshd -T -f %s'
      notify: Restart SSH service

  handlers:
    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
